name: citra-publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # Ampliar la memoria Swap para evitar fallos por falta de RAM
      - name: Free Up Disk Space and Setup Swap
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Licenses and Install NDK
        run: |
          yes | sdkmanager --licenses || true
          sdkmanager "ndk;25.1.8937393" "build-tools;34.0.0"

      - name: Build Android APK with Info Log
        run: |
          cd src/android
          chmod +x gradlew
          export ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/25.1.8937393
          ./gradlew :app:assembleRelease --info

      - name: Upload Real APK
        uses: actions/upload-artifact@v4
        with:
          name: Aether-Android-APK
          path: src/android/app/build/outputs/apk/release/*.apk
