name: citra-publish

on:
  workflow_dispatch:
    inputs:
      nightly:
        description: 'Trigger nightly build'
        required: false
        default: 'true'
      canary:
        description: 'Trigger canary build'
        required: false
        default: 'true'

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Pre-checkout
        with:
          submodules: false
      - run: npm install execa@5
      - uses: actions/checkout@v4
        name: Checkout
        with:
          path: 'citra-merge'
          fetch-depth: 0
          submodules: true
      - uses: actions/github-script@v7
        name: 'Update and tag new commits'
        with:
          script: |
            const execa = require("execa");
            const tagAndPush = require('./.github/workflows/ci-merge.js').tagAndPush;
            process.chdir('${{ github.workspace }}/citra-merge');
            tagAndPush(github, context.repo.owner, `${context.repo.repo}-nightly`, execa);
  canary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Pre-checkout
        with:
          submodules: false
      - run: npm install execa@5
      - uses: actions/checkout@v4
        name: Checkout
        with:
          path: 'citra-merge'
          fetch-depth: 0
          submodules: true
      - uses: actions/github-script@v7
        name: 'Check and merge canary changes'
        with:
          script: |
            const execa = require("execa");
            const mergebot = require('./.github/workflows/ci-merge.js').mergebot;
            process.chdir('${{ github.workspace }}/citra-merge');
            mergebot(github, context, execa);
